Update package.json version to current sprint
microsoft/azure-pipelines-tasks-common-packages pull request #284
Opened 2024-02-21 13:44 UTC by viralpandya

2024-02-21 13:56 UTC, LeftTwixWand commented
This PR is bump of npm package version after this PR: #271

2024-02-21 13:56 UTC, LeftTwixWand commented
This PR is bump of npm version for this PR: https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/271/files

2024-02-22 21:11 UTC, DenisRumyantsev approved these changes

2024-02-23 18:11 UTC, jmyersmsft requested changes

2024-02-23 18:11 UTC, jmyersmsft commented on common-npm-packages/packaging-common/universal/ArtifactToolUtilities.ts
> +        if (process.env.PROCESSOR_ARCHITEW6432 != null)
Please follow our existing code style in both files -- 4 space indent, no tab characters, opening brace on same line

2024-02-23 19:30 UTC, merged